export default console
export const {
  'Console': Console,
  'assert': assert,
  'clear': clear,
  'context': context,
  'count': count,
  'countReset': countReset,
  'debug': debug,
  'dir': dir,
  'dirxml': dirxml,
  'error': error,
  'group': group,
  'groupCollapsed': groupCollapsed,
  'groupEnd': groupEnd,
  'info': info,
  'log': log,
  'markTimeline': markTimeline,
  'profile': profile,
  'profileEnd': profileEnd,
  'table': table,
  'time': time,
  'timeEnd': timeEnd,
  'timeStamp': timeStamp,
  'timeline': timeline,
  'timelineEnd': timelineEnd,
  'trace': trace,
  'warn': warn,
} = console