export default os
export const {
  'EOL': EOL,
  'arch': arch,
  'constants': constants,
  'cpus': cpus,
  'endianness': endianness,
  'freemem': freemem,
  'getNetworkInterfaces': getNetworkInterfaces,
  'homedir': homedir,
  'hostname': hostname,
  'loadavg': loadavg,
  'networkInterfaces': networkInterfaces,
  'platform': platform,
  'release': release,
  'tmpDir': tmpDir,
  'tmpdir': tmpdir,
  'totalmem': totalmem,
  'type': type,
  'uptime': uptime,
  'userInfo': userInfo,
} = os