export default util
export const {
  'TextDecoder': TextDecoder,
  'TextEncoder': TextEncoder,
  'callbackify': callbackify,
  'debug': debug,
  'debuglog': debuglog,
  'deprecate': deprecate,
  'error': error,
  'format': format,
  'getSystemErrorName': getSystemErrorName,
  'inherits': inherits,
  'inspect': inspect,
  'isArray': isArray,
  'isBoolean': isBoolean,
  'isBuffer': isBuffer,
  'isDate': isDate,
  'isError': isError,
  'isFunction': isFunction,
  'isNull': isNull,
  'isNullOrUndefined': isNullOrUndefined,
  'isNumber': isNumber,
  'isObject': isObject,
  'isPrimitive': isPrimitive,
  'isRegExp': isRegExp,
  'isString': isString,
  'isSymbol': isSymbol,
  'isUndefined': isUndefined,
  'log': log,
  'print': print,
  'promisify': promisify,
  'puts': puts,
} = util