
const nodeRequire = require;
(function(){
  debugger
  function h(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function l(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:h(a)}}function n(a){if(!(a instanceof Array)){a=l(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var p="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},q;
if("function"==typeof Object.setPrototypeOf)q=Object.setPrototypeOf;else{var r;a:{var t={M:!0},u={};try{u.__proto__=t;r=u.M;break a}catch(a){}r=!1}q=r?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var v=q,w="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,x="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function y(a,b){if(b){var c=w;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&x(c,a,{configurable:!0,writable:!0,value:b})}}
y("Promise",function(a){function b(a){this.l=0;this.D=void 0;this.g=[];var b=this.v();try{a(b.resolve,b.reject)}catch(m){b.reject(m)}}function c(){this.b=null}function d(a){return a instanceof b?a:new b(function(b){b(a)})}if(a)return a;c.prototype.G=function(a){null==this.b&&(this.b=[],this.N());this.b.push(a)};c.prototype.N=function(){var a=this;this.H(function(){a.T()})};var e=w.setTimeout;c.prototype.H=function(a){e(a,0)};c.prototype.T=function(){for(;this.b&&this.b.length;){var a=this.b;this.b=
[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(B){this.O(B)}}}this.b=null};c.prototype.O=function(a){this.H(function(){throw a;})};b.prototype.v=function(){function a(a){return function(e){c||(c=!0,a.call(b,e))}}var b=this,c=!1;return{resolve:a(this.$),reject:a(this.C)}};b.prototype.$=function(a){if(a===this)this.C(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.ba(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=
!0;break a;default:c=!1}c?this.Z(a):this.J(a)}};b.prototype.Z=function(a){var b=void 0;try{b=a.then}catch(m){this.C(m);return}"function"==typeof b?this.ca(b,a):this.J(a)};b.prototype.C=function(a){this.K(2,a)};b.prototype.J=function(a){this.K(1,a)};b.prototype.K=function(a,b){if(0!=this.l)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.l);this.l=a;this.D=b;this.U()};b.prototype.U=function(){if(null!=this.g){for(var a=0;a<this.g.length;++a)f.G(this.g[a]);this.g=null}};
var f=new c;b.prototype.ba=function(a){var b=this.v();a.o(b.resolve,b.reject)};b.prototype.ca=function(a,b){var c=this.v();try{a.call(b,c.resolve,c.reject)}catch(B){c.reject(B)}};b.prototype.then=function(a,c){function e(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(T){g(T)}}:b}var d,g,f=new b(function(a,b){d=a;g=b});this.o(e(a,d),e(c,g));return f};b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.o=function(a,b){function c(){switch(e.l){case 1:a(e.D);break;case 2:b(e.D);
break;default:throw Error("Unexpected state: "+e.l);}}var e=this;null==this.g?f.G(c):this.g.push(c)};b.resolve=d;b.reject=function(a){return new b(function(b,c){c(a)})};b.race=function(a){return new b(function(b,c){for(var e=l(a),f=e.next();!f.done;f=e.next())d(f.value).o(b,c)})};b.all=function(a){var c=l(a),e=c.next();return e.done?d([]):new b(function(a,b){function f(b){return function(c){g[b]=c;m--;0==m&&a(g)}}var g=[],m=0;do g.push(void 0),m++,d(e.value).o(f(g.length-1),b),e=c.next();while(!e.done)})};
return b});function z(){z=function(){};w.Symbol||(w.Symbol=A)}var A=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();function C(){z();var a=w.Symbol.iterator;a||(a=w.Symbol.iterator=w.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&x(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return D(h(this))}});C=function(){}}function D(a){C();a={next:a};a[w.Symbol.iterator]=function(){return this};return a}
function E(){this.i=!1;this.c=null;this.s=void 0;this.f=1;this.I=this.R=0;this.h=null}function F(a){if(a.i)throw new TypeError("Generator is already running");a.i=!0}E.prototype.j=function(a){this.s=a};E.prototype.m=function(a){this.h={S:a,W:!0};this.f=this.R||this.I};E.prototype.return=function(a){this.h={return:a};this.f=this.I};function G(a,b){a.f=2;return{value:b}}function H(a){this.a=new E;this.X=a}
H.prototype.j=function(a){F(this.a);if(this.a.c)return I(this,this.a.c.next,a,this.a.j);this.a.j(a);return J(this)};function K(a,b){F(a.a);var c=a.a.c;if(c)return I(a,"return"in c?c["return"]:function(a){return{value:a,done:!0}},b,a.a.return);a.a.return(b);return J(a)}H.prototype.m=function(a){F(this.a);if(this.a.c)return I(this,this.a.c["throw"],a,this.a.j);this.a.m(a);return J(this)};
function I(a,b,c,d){try{var e=b.call(a.a.c,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.a.i=!1,e;var f=e.value}catch(g){return a.a.c=null,a.a.m(g),J(a)}a.a.c=null;d.call(a.a,f);return J(a)}function J(a){for(;a.a.f;)try{var b=a.X(a.a);if(b)return a.a.i=!1,{value:b.value,done:!1}}catch(c){a.a.s=void 0,a.a.m(c)}a.a.i=!1;if(a.a.h){b=a.a.h;a.a.h=null;if(b.W)throw b.S;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function L(a){this.next=function(b){return a.j(b)};this.throw=function(b){return a.m(b)};this.return=function(b){return K(a,b)};C();this[Symbol.iterator]=function(){return this}}function M(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(d,e){function f(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(f,e)}f(a.next())})}y("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}});
y("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=b[c];if(f===a||Object.is(f,a))return!0}return!1}});
y("String.prototype.includes",function(a){return a?a:function(a,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(a,c||0)}});
var N="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)Object.prototype.hasOwnProperty.call(d,e)&&(a[e]=d[e])}return a};y("Object.assign",function(a){return a||N});var O=nodeRequire("os").V,P=/\s+at.*(?:\(|\s)(.*)\)?/,Q=/^(?:(?:(?:node|(?:internal\/[\w/]*|.*node_modules\/(?:IGNORED_MODULES)\/.*)?\w+)\.js:\d+:\d+)|native)/,aa=O();
function R(a,b){b=void 0===b?{}:b;var c=void 0===b.B?!1:b.B,d=new RegExp(Q.source.replace("IGNORED_MODULES",(void 0===b.A?["pirates"]:b.A).join("|")));return a.replace(/\\/g,"/").split("\n").filter(function(a){a=a.match(P);if(null===a||!a[1])return!0;a=a[1];return a.includes(".app/Contents/Resources/electron.asar")||a.includes(".app/Contents/Resources/default_app.asar")?!1:!d.test(a)}).filter(function(a){return""!==a.trim()}).map(function(a){return c?a.replace(P,function(a,b){return a.replace(b,b.replace(aa,
"~"))}):a}).join("\n")};function ba(a,b,c){c=void 0===c?!1:c;return function(d){var e=arguments.callee.caller;var f=Error().stack;var g=2,k=!0;g=void 0===g?0:g;k=void 0===k?!1:k;if(0!==g||k)f=f.split("\n",k?g+1:Number.Infinity),f=k?f[f.length-1]:f.slice(g).join("\n");k=(g=d instanceof Error)?d.message:d;e=["Error: "+k].concat(n(null!==e&&a===e||c?[b]:[f,b])).join("\n");e=R(e);return Object.assign(g?d:Error(),{message:k,stack:e})}}R&&R.F&&(R=R.default);function S(a){var b=2+(a?1:0);var c=Error().stack;b=void 0===b?0:b;var d=void 0===d?!1:d;0!==b||d?(c=c.split("\n",d?b+1:Number.Infinity),b=d?c[c.length-1]:c.slice(b).join("\n")):b=c;return ba(arguments.callee.caller,b,a)};var ca=nodeRequire("os").V,U=/\s+at.*(?:\(|\s)(.*)\)?/,da=/^(?:(?:(?:node|(?:internal\/[\w/]*|.*node_modules\/(?:IGNORED_MODULES)\/.*)?\w+)\.js:\d+:\d+)|native)/,ea=ca();
function V(a,b){b=void 0===b?{}:b;var c=void 0===b.B?!1:b.B,d=new RegExp(da.source.replace("IGNORED_MODULES",(void 0===b.A?["pirates"]:b.A).join("|")));return a.replace(/\\/g,"/").split("\n").filter(function(a){a=a.match(U);if(null===a||!a[1])return!0;a=a[1];return a.includes(".app/Contents/Resources/electron.asar")||a.includes(".app/Contents/Resources/default_app.asar")?!1:!d.test(a)}).filter(function(a){return""!==a.trim()}).map(function(a){return c?a.replace(U,function(a,b){return a.replace(b,
b.replace(ea,"~"))}):a}).join("\n")};var W=nodeRequire("stream").ea;S&&S.F&&(S=S.default);V&&V.F&&(V=V.default);
function X(a){a=void 0===a?{}:a;var b=Object.assign({},a),c=void 0===a.w?S(!0):a.w;a=(delete b.w,b);var d=W.call(this,a)||this;var e=a.P,f=a.aa;d.u=[];d.L=new Promise(function(a,b){d.ha("finish",function(){a(e?Buffer.concat(d.u):d.u.join(""));d.u=[]});d.once("error",function(a){if(-1==a.stack.indexOf("\n"))a=c(a),b(a);else{var d=V(a.stack);a.stack=d;b(a)}});f&&(f.once("error",function(a){return d.fa("error",a)}),f.ia(d))});return d}X.prototype=p(W.prototype);X.prototype.constructor=X;
if(v)v(X,W);else for(var Y in W)if("prototype"!=Y)if(Object.defineProperties){var Z=Object.getOwnPropertyDescriptor(W,Y);Z&&Object.defineProperty(X,Y,Z)}else X[Y]=W[Y];X.ja=W.prototype;w.Object.defineProperties(X.prototype,{Y:{configurable:!0,enumerable:!0,get:function(){return this.L}}});function fa(a){var b={ga:!0};b=void 0===b?{P:!1}:b;var c,d,e;return M(new L(new H(function(f){if(1==f.f)return c=new X(Object.assign({},{aa:a},b,{w:S(!0)})),d=c.Y,G(f,d);e=f.s;return f.return(e)})))};var ha=nodeRequire("stream").da;(function(){var a,b;return M(new L(new H(function(c){if(1==c.f)return a=new ha({read:function(){this.push("ok");this.push(null)}}),G(c,fa(a));b=c.s;console.log(b);c.f=0})))})();
}).call(this)
